/**
 * 英雄俗称表。
 *
 * **这是手工维护的社区叫法，不是官方资料。** 官方名以 `npc_heroes` 的 datafeed 为准
 * （见 `/draft-data.json` 的 `heroes[].name` / `nameEn`），这里只补玩家实际会说的那些：
 * 中文俗称（敌法、火猫、影魔）、DOTA1 时期沿用下来的旧名（剑圣、屠夫）、
 * 以及英文缩写（AM、SF、QoP）。
 *
 * 键是**官方中文名**，不是 id。这样表本身可以被人直接读和改，也不用担心 id 写错；
 * 代价是英雄改名时这条会对不上，所以 `resolveHeroQuery` 会把对不上的键报出来
 * （`scripts/mcp.check.mjs` 会拿真实的英雄表核一遍）。这与 `src/data/heroTraits.ts`
 * 里 `resolveHeroNames` 的态度一致：宁可报出来让人看，不要模糊匹配悄悄指错人。
 *
 * 收录标准：
 * - 只在社区里**真的有人这么叫**，且不会指向另一个英雄。像「小娜迦」这种带前缀区分的不收
 *   （娜迦海妖本身就够短），避免两份名字互相抢；
 * - 同一个俗称只挂一个英雄。「幻刺」挂幻影刺客、「猴子」挂齐天大圣，都有唯一性；
 * - 英文只收常见缩写与 DOTA1 旧名，不收随意的大小写变体（匹配时会忽略大小写与连字符）。
 */
export const HERO_ALIASES = {
	敌法师: ['敌法', 'DF', 'AM', 'anti mage', 'magina'],
	斧王: ['Axe', '斧'],
	祸乱之源: ['祸乱', 'Bane'],
	血魔: ['BS', 'bloodseeker'],
	水晶室女: ['冰女', 'CM', 'crystal maiden'],
	卓尔游侠: ['小黑', 'DR', 'drow'],
	撼地者: ['小牛', '神牛', 'ES', 'earthshaker', '撼地神牛'],
	主宰: ['剑圣', 'Jugg', 'juggernaut'],
	米拉娜: ['白虎', '月女', 'POM', 'mirana', 'potm'],
	变体精灵: ['水人', 'Morph', 'morphling'],
	影魔: ['SF', 'nevermore', 'shadow fiend'],
	幻影长矛手: ['长矛手', 'PL', 'phantom lancer', '猴子王'],
	帕克: ['精灵龙', '仙女龙', 'Puck'],
	帕吉: ['屠夫', 'Pudge', '胖子'],
	雷泽: ['电魂', 'Razor', '闪电幽魂'],
	沙王: ['SK', 'sand king', 'Crixalis'],
	风暴之灵: ['蓝猫', '风暴', 'Storm', 'storm spirit'],
	斯温: ['SV', '流浪剑客', 'Sven'],
	小小: ['Tiny', '山岭巨人'],
	复仇之魂: ['复仇', 'VS', 'vengeful spirit'],
	风行者: ['风行', 'WR', 'windranger'],
	宙斯: ['Zeus', '雷神'],
	昆卡: ['船长', 'Kunkka', '海军上将'],
	莉娜: ['火女', 'Lina'],
	莱恩: ['恶魔巫师', 'Lion'],
	暗影萨满: ['小Y', 'SS', 'shadow shaman', '萨满'],
	斯拉达: ['大鱼人', 'Slardar', '大鱼'],
	潮汐猎人: ['潮汐', 'TH', 'tidehunter'],
	巫医: ['WD', 'witch doctor'],
	巫妖: ['Lich'],
	力丸: ['隐形刺客', 'SA', 'Riki', '隐刺'],
	谜团: ['Enigma', '黑洞'],
	修补匠: ['TK', 'Tinker', '修补'],
	狙击手: ['火枪', 'Sniper', '矮子'],
	瘟疫法师: ['Necro', '死灵法师', 'Necrophos'],
	术士: ['WL', 'Warlock'],
	兽王: ['BM', 'Beastmaster'],
	痛苦女王: ['女王', 'QoP', 'QOP', 'queen of pain'],
	剧毒术士: ['剧毒', 'Venomancer', 'Venom'],
	虚空假面: ['虚空', 'FV', 'Void', 'faceless void'],
	冥魂大帝: ['骷髅王', 'WK', 'SNK', 'wraith king'],
	死亡先知: ['DP', 'death prophet'],
	幻影刺客: ['幻刺', 'PA', 'Mortred', 'phantom assassin'],
	帕格纳: ['骨法', 'Pugna'],
	圣堂刺客: ['圣堂', 'TA', 'templar assassin', '拉娜雅'],
	冥界亚龙: ['毒龙', 'Viper', '亚龙'],
	露娜: ['月骑', 'Luna', 'moon rider'],
	龙骑士: ['龙骑', 'DK', 'dragon knight'],
	戴泽: ['暗牧', 'Dazzle', '牧师'],
	发条技师: ['发条', 'CW', 'Clockwerk'],
	拉席克: ['老鹿', 'Leshrac'],
	自然先知: ['先知', 'NP', 'nature s prophet', '法里奥'],
	噬魂鬼: ['小狗', 'LS', 'Naix', 'lifestealer'],
	黑暗贤者: ['黑贤', 'DS', 'dark seer'],
	克林克兹: ['骨弓', 'Clinkz', 'Bone'],
	全能骑士: ['全能', 'OK', 'Omniknight'],
	魅惑魔女: ['小鹿', 'Enchantress'],
	哈斯卡: ['神灵武士', '神灵', 'Huskar'],
	暗夜魔王: ['夜魔', 'NS', 'night stalker', '巴拉森'],
	育母蜘蛛: ['蜘蛛', 'Broodmother', 'Brood'],
	赏金猎人: ['赏金', 'BH', 'bounty hunter'],
	编织者: ['蚂蚁', 'Weaver'],
	杰奇洛: ['双头龙', 'Jakiro', 'THD'],
	蝙蝠骑士: ['蝙蝠', 'Batrider', 'Bat'],
	陈: ['Chen', '圣骑士'],
	幽鬼: ['SPE', 'Spectre', 'Mercurial'],
	远古冰魄: ['冰魂', 'AA', 'ancient apparition'],
	末日使者: ['末日', 'Doom'],
	熊战士: ['拍拍熊', '拍拍', 'Ursa'],
	裂魂人: ['白牛', 'SB', 'spirit breaker'],
	矮人直升机: ['直升机', '飞机', 'Gyro', 'Gyrocopter'],
	炼金术士: ['炼金', 'Alchemist', 'GA'],
	祈求者: ['卡尔', 'Invoker', 'Kael'],
	沉默术士: ['沉默', 'Silencer'],
	殁境神蚀者: ['黑鸟', 'OD', 'outworld destroyer', '黑曜毁灭者'],
	狼人: ['Lycan', '狼'],
	酒仙: ['熊猫', 'Brewmaster', 'Panda'],
	暗影恶魔: ['SD', 'shadow demon', '暗恶魔'],
	独行德鲁伊: ['德鲁伊', '熊德', 'LD', 'lone druid'],
	混沌骑士: ['CK', 'chaos knight', '混沌'],
	米波: ['Meepo', '地卜师'],
	树精卫士: ['大树', 'Treant', 'treant protector'],
	食人魔魔法师: ['蓝胖', 'OM', 'ogre magi', '食人魔'],
	不朽尸王: ['尸王', 'Undying', '不朽'],
	拉比克: ['Rubick', '大魔导师'],
	干扰者: ['萨尔', 'Disruptor', 'Disrupt'],
	司夜刺客: ['小强', 'NA', 'Nyx', 'nyx assassin'],
	娜迦海妖: ['Naga', 'naga siren'],
	光之守卫: ['光法', 'KotL', 'keeper of the light'],
	艾欧: ['小精灵', 'Io', 'Wisp', '精灵'],
	维萨吉: ['死灵龙', 'Visage', '维萨奇'],
	斯拉克: ['小鱼人', '小鱼', 'Slark'],
	美杜莎: ['一姐', 'Medusa', 'Gorgon'],
	巨魔战将: ['巨魔', 'TW', 'Troll', 'troll warlord'],
	半人马战行者: ['半人马', '人马', 'Centaur'],
	马格纳斯: ['猛犸', 'Magnus', '玛格纳斯'],
	伐木机: ['Timbersaw', 'TS2', '伐木'],
	钢背兽: ['刚背', 'BB', 'Bristleback', '刚背兽'],
	巨牙海民: ['海民', 'Tusk'],
	天怒法师: ['天怒', 'SM', 'Skywrath', 'skywrath mage'],
	亚巴顿: ['Abaddon', 'LOA', 'lord of avernus'],
	上古巨神: ['大牛', 'ET', 'elder titan', '巨神'],
	军团指挥官: ['军团', 'LC', 'legion commander'],
	工程师: ['炸弹人', '炸弹', 'Techies'],
	灰烬之灵: ['火猫', 'Ember', 'ember spirit'],
	大地之灵: ['土猫', 'Earth', 'earth spirit'],
	孽主: ['Underlord', '深渊领主'],
	恐怖利刃: ['TB', 'Terrorblade', '灵魂守卫'],
	凤凰: ['Phoenix', '火鸟'],
	神谕者: ['神谕', 'Oracle'],
	寒冬飞龙: ['冰龙', 'WW', 'Wyvern', 'winter wyvern'],
	天穹守望者: ['弧光', 'AW', 'arc warden', '弧光守望者'],
	齐天大圣: ['猴子', 'MK', 'monkey king', '大圣'],
	邪影芳灵: ['小仙女', 'DW', 'dark willow', '花仙子'],
	石鳞剑士: ['Pango', 'Pangolier', '剑士'],
	天涯墨客: ['墨客', 'Grimstroke', '毛笔'],
	森海飞霞: ['松鼠', 'Hoodwink', '小松鼠'],
	虚无之灵: ['紫猫', 'Void Spirit', '虚无'],
	电炎绝手: ['老奶奶', 'Snapfire', '奶奶'],
	玛尔斯: ['Mars', '战神'],
	百戏大王: ['小丑', 'Ringmaster', '戏王'],
	破晓辰星: ['破晓', 'Dawnbreaker', '晨曦'],
	玛西: ['Marci'],
	獸: ['Primal Beast', '原始兽', '兽'],
	琼英碧灵: ['Muerta', '碧灵', '女枪'],
	凯: ['Kez'],
	朗戈: ['Largo'],
};
